project:
  type: website
  output-dir: docs # command to allow publishing using docs (https://quarto.org/docs/publishing/github-pages.html)

website:

  title: "Biologia della Conservazione 23/24"
  reader-mode: true
  page-navigation: true
  description: ""
  site-url: https://giulianocolosimo.github.com
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [issue]
  open-graph:
    locale: en_US
  
  navbar:
    search: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Calendar"
        href: calendar.qmd
      - text: "Contact"
        href: contact.qmd

  sidebar:
    logo: "./figures/avatar.jpg"
    pinned: false
    align: center
    style: "docked"
    background: light
    collapse-level: 2
    contents:
      - section: "Classes"
        title: "Classes"
        contents: 
          - href: ./classes/1/class_1.html
            text: "Class 1 - Introduction to conservation biology"
          - href: ./classes/2/class_2.html
            text: "Class 2 - Biodiversity"
          - href: ./classes/3/class_3.html
            text: "Class 3 - Biodiversity & Extinctions"  
          - href: ./classes/4/class_4.html
            text: "Class 4 - Populations (1)"  
          - href: ./classes/5/class_5.html
            text: "Class 5 - Populations (2) - Intro to Conservation Genetics"  
          - href: ./classes/6/class_6.html
            text: "Class 6 - Conservation Genetics"  
          - href: ./classes/7/class_7.html
            text: "Class 7 - Genetic Drift/Effective Population Size"  
          - href: ./classes/8/class_8.html
            text: "Class 8 - Manuscript discussion-Genetic Drift/Effective Population Size"  
          - href: ./classes/9/class_9.html
            text: "Class 9 - Manuscript discussion-Genetic Drift/Effective Population Size"  
          - href: ./classes/10/class_10.html
            text: "Class 10 - Inbreeding"  
          - href: ./classes/11/class_11.html
            text: "Class 11 - Arguments review for mid term"  
          - href: ./classes/12/class_12.html
            text: "Class 12 - Mid-term exam revision/Genetic load"  
          - href: ./classes/13/class_13.html
            text: "Class 13 - Population Structure/Hybridization_1"  
          - href: ./classes/14/class_14.html
            text: "Class 14 - Population Structure/Hybridization_2"  
          - href: ./classes/15/class_15.html
            text: "Class 15 - Heritability"  
          - href: ./classes/16/class_16.html
            text: "Class 16 - Population Viability Analysis"  
          - href: ./classes/17/class_17.html
            text: "Class 17 - Invasive Species"  
          - href: ./classes/18/class_18.html
            text: "Class 18 - CITES"  
          - href: ./classes/19/class_19.html
            text: "Class 19 - CITES presentation by GdF"  
          - href: ./classes/20/class_20.html
            text: "Class 20 - Climate change"  
          - href: ./classes/21/class_21.html
            text: "Class 21 - Climate change"  


    tools:
      - icon: envelope
        url: "mailto:giuliano.colosimo@protonmail.com"

  page-footer:
    left: "© Copyright 2024 Giuliano Colosimo"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/). Inspiration for this site comes from [here](https://www.mm218.dev)."
    background: dark
    

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
